### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'first_stage_model'

### ISSUE THREAD

**Issue by throttlekitty** [deforum-art/sd-webui-modelscope-text2video#3]
I get this on pressing generate, and I'm not certain if it's because i'm currently running torch2.

Arguments: ('test1', '', 20, 24, 7, 256, 256, 0.0, False) {}
Traceback (most recent call last):
  File "C:\stable-diffusion\a1-sd-webui\modules\call_queue.py", line 56, in f
    res = list(func(*args, **kwargs))
  File "C:\stable-diffusion\a1-sd-webui\modules\call_queue.py", line 37, in f
    res = func(*args, **kwargs)
  File "C:\stable-diffusion\a1-sd-webui\extensions\sd-webui-modelscope-text2video\scripts\modelscope-text2vid.py", line 52, in process
    lowvram.setup_for_low_vram(sd_model, cmd_opts.medvram)
  File "C:\stable-diffusion\a1-sd-webui\modules\lowvram.py", line 42, in setup_for_low_vram
    first_stage_model = sd_model.first_stage_model
AttributeError: 'NoneType' object has no attribute 'first_stage_model'

Traceback (most recent call last):
  File "C:\stable-diffusion\a1-sd-webui\venv\lib\site-packages\gradio\routes.py", line 337, in run_predict
    output = await app.get_blocks().process_api(
  File "C:\stable-diffusion\a1-sd-webui\venv\lib\site-packages\gradio\blocks.py", line 1018, in process_api
    data = self.postprocess_data(fn_index, result["prediction"], state)
  File "C:\stable-diffusion\a1-sd-webui\venv\lib\site-packages\gradio\blocks.py", line 956, in postprocess_data
    prediction_value = block.postprocess(prediction_value)
  File "C:\stable-diffusion\a1-sd-webui\venv\lib\site-packages\gradio\components.py", line 1860, in postprocess
    returned_format = y.split(".")[-1].lower()
AttributeError: 'tuple' object has no attribute 'split'

**Comment by kabachuha** [comment]
Hmm, looks like an external webui/torch2 issue, because I was running it on torch 1.12 and the latest webui commit

**Comment by kabachuha** [comment]
If you have enough vram, try uncommenting the lowvram-related lines in the main file

**Comment by throttlekitty** [comment]
I jumped back to a fresh vanilla venv and still get the same error. Commenting the lowvram lines gives me this:

Arguments: ('test', '', 20, 24, 7, 256, 256, 0.0, False) {}
Traceback (most recent call last):
  File "C:\stable-diffusion\a1-sd-webui\modules\call_queue.py", line 56, in f
    res = list(func(*args, **kwargs))
  File "C:\stable-diffusion\a1-sd-webui\modules\call_queue.py", line 37, in f
    res = func(*args, **kwargs)
  File "C:\stable-diffusion\a1-sd-webui\extensions\sd-webui-modelscope-text2video\scripts\modelscope-text2vid.py", line 54, in process
    return outdir_current + os.path.sep + f"vid.mp4"
UnboundLocalError: local variable 'outdir_current' referenced before assignment

Traceback (most recent call last):
  File "C:\stable-diffusion\a1-sd-webui\venv\lib\site-packages\gradio\routes.py", line 337, in run_predict
    output = await app.get_blocks().process_api(
  File "C:\stable-diffusion\a1-sd-webui\venv\lib\site-packages\gradio\blocks.py", line 1018, in process_api
    data = self.postprocess_data(fn_index, result["prediction"], state)
  File "C:\stable-diffusion\a1-sd-webui\venv\lib\site-packages\gradio\blocks.py", line 956, in postprocess_data
    prediction_value = block.postprocess(prediction_value)
  File "C:\stable-diffusion\a1-sd-webui\venv\lib\site-packages\gradio\components.py", line 1860, in postprocess
    returned_format = y.split(".")[-1].lower()
AttributeError: 'tuple' object has no attribute 'split'

**Comment by kabachuha** [comment]
```
UnboundLocalError: local variable 'outdir_current' referenced before assignment
```
Oh, that's another error now 👀

I need to get some hours of sleep after releasing this, so wait for a tiny bit

**Comment by saphtea** [comment]
Haha sleep well! Doing some testing over here, trying uncommenting lines, downgraded to 1.13.1 in the venv (as I had that working with the main code separate from automatic1111). Lemme know if there's anything further you need tested for this issue!

**Comment by matteo101man** [comment]
I've actually been experiencing the exact same issue, and I'm on pytorch 1.13.1. Look forward to the solutions haha

**Comment by matteo101man** [comment]
FFMPEG Video (sorry, no audio) stitching done in 0.05 seconds!
t2v complete, result saved at C:\StableDiffusion\automatic1111 new\outputs/img2img-images\text2video-modelscope\20230319214714
Error completing request
Arguments: ('man jumping up and down', '', 20, 24, 7, 256, 256, 0.0, False) {}
Traceback (most recent call last):
  File "C:\StableDiffusion\automatic1111 new\modules\call_queue.py", line 56, in f
    res = list(func(*args, **kwargs))
  File "C:\StableDiffusion\automatic1111 new\modules\call_queue.py", line 37, in f
    res = func(*args, **kwargs)
  File "C:\StableDiffusion\automatic1111 new\extensions\sd-webui-modelscope-text2video-main\scripts\modelscope-text2vid.py", line 52, in process
    lowvram.setup_for_low_vram(sd_model, cmd_opts.medvram)
  File "C:\StableDiffusion\automatic1111 new\modules\lowvram.py", line 42, in setup_for_low_vram
    first_stage_model = sd_model.first_stage_model
AttributeError: 'NoneType' object has no attribute 'first_stage_model'

Traceback (most recent call last):
  File "C:\StableDiffusion\automatic1111 new\venv\lib\site-packages\gradio\routes.py", line 321, in run_predict
    output = await app.blocks.process_api(
  File "C:\StableDiffusion\automatic1111 new\venv\lib\site-packages\gradio\blocks.py", line 1016, in process_api
    data = self.postprocess_data(fn_index, result["prediction"], state)
  File "C:\StableDiffusion\automatic1111 new\venv\lib\site-packages\gradio\blocks.py", line 962, in postprocess_data
    prediction_value = block.postprocess(prediction_value)
  File "C:\StableDiffusion\automatic1111 new\venv\lib\site-packages\gradio\components.py", line 1782, in postprocess
    returned_format = y.split(".")[-1].lower()
AttributeError: 'tuple' object has no attribute 'split'

This is what I get, and I have no args set for medvram or lowvram (I have 24gb)

**Comment by Cubey42** [comment]
Traceback (most recent call last):
  File "H:\NovelAI\stable-diffusion-webui\modules\call_queue.py", line 56, in f
    res = list(func(*args, **kwargs))
  File "H:\NovelAI\stable-diffusion-webui\modules\call_queue.py", line 37, in f
    res = func(*args, **kwargs)
  File "H:\NovelAI\stable-diffusion-webui\extensions\sd-webui-modelscope-text2video\scripts\modelscope-text2vid.py", line 52, in process
    lowvram.setup_for_low_vram(sd_model, cmd_opts.medvram)
  File "H:\NovelAI\stable-diffusion-webui\modules\lowvram.py", line 42, in setup_for_low_vram
    first_stage_model = sd_model.first_stage_model
AttributeError: 'NoneType' object has no attribute 'first_stage_model'

Traceback (most recent call last):
  File "H:\NovelAI\stable-diffusion-webui\venv\lib\site-packages\gradio\routes.py", line 337, in run_predict
    output = await app.get_blocks().process_api(
  File "H:\NovelAI\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1018, in process_api
    data = self.postprocess_data(fn_index, result["prediction"], state)
  File "H:\NovelAI\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 956, in postprocess_data
    prediction_value = block.postprocess(prediction_value)
  File "H:\NovelAI\stable-diffusion-webui\venv\lib\site-packages\gradio\components.py", line 1860, in postprocess
    returned_format = y.split(".")[-1].lower()
AttributeError: 'tuple' object has no attribute 'split'

I got this as well but I didn't make any changes, it just appeared after the first issue.
also the code references a folder where it looks like the model dumps the images it generated before actually stitching them together for a video. stable-diffusion-webui\outputs\img2img-images\text2video-modelscope but going there the first time will crash explorer, but then the frames will be in the folder

**Comment by Devalinor** [comment]
Same here
```
Traceback (most recent call last):
  File "F:\UI\modules\call_queue.py", line 56, in f
    res = list(func(*args, **kwargs))
  File "F:\UI\modules\call_queue.py", line 37, in f
    res = func(*args, **kwargs)
  File "F:\UI\extensions\sd-webui-modelscope-text2video\scripts\modelscope-text2vid.py", line 52, in process
    lowvram.setup_for_low_vram(sd_model, cmd_opts.medvram)
  File "F:\UI\modules\lowvram.py", line 42, in setup_for_low_vram
    first_stage_model = sd_model.first_stage_model
AttributeError: 'NoneType' object has no attribute 'first_stage_model'

Traceback (most recent call last):
  File "F:\UI\venv\lib\site-packages\gradio\routes.py", line 337, in run_predict
    output = await app.get_blocks().process_api(
  File "F:\UI\venv\lib\site-packages\gradio\blocks.py", line 1018, in process_api
    data = self.postprocess_data(fn_index, result["prediction"], state)
  File "F:\UI\venv\lib\site-packages\gradio\blocks.py", line 956, in postprocess_data
    prediction_value = block.postprocess(prediction_value)
  File "F:\UI\venv\lib\site-packages\gradio\components.py", line 1860, in postprocess
    returned_format = y.split(".")[-1].lower()
AttributeError: 'tuple' object has no attribute 'split'
```

**Comment by throttlekitty** [comment]
It works, thanks! Just letting you know this runs on torch2 as well.
