### ISSUE TITLE
[Bug]: AssertionError: function with index 495 not defined.

### ISSUE THREAD

**Issue by ThatDocBoi** [deforum-art/sd-webui-modelscope-text2video#47]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### Are you using the latest version of the extension?

- [X] I have the modelscope text2video extension updated to the lastest version and I still have the issue.

### What happened?

I just updated the extension and now I'm getting this error. Worked fine 5 hours ago.
### Steps to reproduce the problem

1. Open webui-user.bat
2. Under ModelScope tab input any prompt with stock settings
3. Press Generate

### What should have happened?

It should generate the video not return an error

### WebUI and Deforum extension Commit IDs

webui commit id - commit: [a9fed7c3]

txt2vid commit id -  092aa42

### What GPU were you using for launching?

RTX 3080 10GB

### On which platform are you launching the webui backend with the extension?

Local PC setup (Windows)

### Settings

![image](https://user-images.githubusercontent.com/60790181/227063639-b84df88f-f309-4f18-9a21-7a0c8a6c2853.png)
![image](https://user-images.githubusercontent.com/60790181/227063653-43eb570e-2a32-47db-9c51-30a92d83bf33.png)

### Console logs

```Shell
venv "A:\stable-diffusion-webui\venv\Scripts\Python.exe"
Python 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Commit hash: a9fed7c364061ae6efb37f797b6b522cb3cf7aa2
Installing requirements for Web UI



Launching Web UI with arguments:
No module 'xformers'. Proceeding without it.
Loading weights [f94d96ebdc] from A:\stable-diffusion-webui\models\Stable-diffusion\HassanBlend1.5.1.2-pruned.safetensors
Creating model from config: A:\stable-diffusion-webui\configs\v1-inference.yaml
LatentDiffusion: Running in eps-prediction mode
DiffusionWrapper has 859.52 M params.
Loading VAE weights found near the checkpoint: A:\stable-diffusion-webui\models\Stable-diffusion\HassanBlend1.5.1.2-pruned.vae.pt
Applying cross attention optimization (Doggettx).
Textual inversion embeddings loaded(5): donut, donut2, donut3, test2, test3
Textual inversion embeddings skipped(2): donut4, test
Model loaded in 16.6s (load weights from disk: 0.3s, create model: 0.3s, apply weights to model: 13.0s, apply half(): 0.6s, load VAE: 0.9s, move model to device: 0.6s, load textual inversion embeddings: 0.8s).
*Deforum ControlNet support: enabled*
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
Startup time: 26.2s (import gradio: 2.3s, import ldm: 1.3s, other imports: 2.4s, list extensions: 0.8s, setup codeformer: 0.1s, load scripts: 1.8s, load SD checkpoint: 16.7s, create ui: 0.6s).
Traceback (most recent call last):
  File "A:\stable-diffusion-webui\venv\lib\site-packages\gradio\routes.py", line 337, in run_predict
    output = await app.get_blocks().process_api(
  File "A:\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1015, in process_api
    result = await self.call_function(
  File "A:\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 795, in call_function
    assert block_fn.fn, f"function with index {fn_index} not defined."
AssertionError: function with index 495 not defined.
Traceback (most recent call last):
  File "A:\stable-diffusion-webui\venv\lib\site-packages\gradio\routes.py", line 337, in run_predict
    output = await app.get_blocks().process_api(
  File "A:\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1015, in process_api
    result = await self.call_function(
  File "A:\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 795, in call_function
    assert block_fn.fn, f"function with index {fn_index} not defined."
AssertionError: function with index 495 not defined.
Traceback (most recent call last):
  File "A:\stable-diffusion-webui\venv\lib\site-packages\gradio\routes.py", line 337, in run_predict
    output = await app.get_blocks().process_api(
  File "A:\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1015, in process_api
    result = await self.call_function(
  File "A:\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 795, in call_function
    assert block_fn.fn, f"function with index {fn_index} not defined."
AssertionError: function with index 495 not defined.
Traceback (most recent call last):
  File "A:\stable-diffusion-webui\venv\lib\site-packages\gradio\routes.py", line 337, in run_predict
    output = await app.get_blocks().process_api(
  File "A:\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1015, in process_api
    result = await self.call_function(
  File "A:\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 795, in call_function
    assert block_fn.fn, f"function with index {fn_index} not defined."
AssertionError: function with index 495 not defined.
Traceback (most recent call last):
  File "A:\stable-diffusion-webui\venv\lib\site-packages\gradio\routes.py", line 337, in run_predict
    output = await app.get_blocks().process_api(
  File "A:\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1015, in process_api
    result = await self.call_function(
  File "A:\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 795, in call_function
    assert block_fn.fn, f"function with index {fn_index} not defined."
AssertionError: function with index 495 not defined.
```

### Additional information

I tried to generate 3 times with each setting (gpu, gpu half precision and cpu) but they all gave the same error.

**Comment by ThatDocBoi** [comment]
Hmm, I restarted it for the third time and now it seems to work. Haven't changed any settings.

**Comment by kabachuha** [comment]
@ThatDocBoi there is the cache problem for Auto. Sometimes if the interface changes the cache stores the previous version of the cache and passes it to gradio instead of making the UI from scratch. And that jeopardizes its work. If you don't want to wait next time, delete your cache.json and cache.json.lock files in the core webui directory and restart it
