### ISSUE TITLE
Images won't be converted to a video

### ISSUE THREAD

**Issue by Devalinor** [deforum-art/sd-webui-modelscope-text2video#6]
The image generation seems to be fine, but the video won't be generated. Any ideas?

```
Traceback (most recent call last):
  File "F:\UI\modules\call_queue.py", line 56, in f
    res = list(func(*args, **kwargs))
  File "F:\UI\modules\call_queue.py", line 37, in f
    res = func(*args, **kwargs)
  File "F:\UI\extensions\sd-webui-modelscope-text2video\scripts\modelscope-text2vid.py", line 52, in process
    lowvram.setup_for_low_vram(sd_model, cmd_opts.medvram)
  File "F:\UI\modules\lowvram.py", line 42, in setup_for_low_vram
    first_stage_model = sd_model.first_stage_model
AttributeError: 'NoneType' object has no attribute 'first_stage_model'

Traceback (most recent call last):
  File "F:\UI\venv\lib\site-packages\gradio\routes.py", line 337, in run_predict
    output = await app.get_blocks().process_api(
  File "F:\UI\venv\lib\site-packages\gradio\blocks.py", line 1018, in process_api
    data = self.postprocess_data(fn_index, result["prediction"], state)
  File "F:\UI\venv\lib\site-packages\gradio\blocks.py", line 956, in postprocess_data
    prediction_value = block.postprocess(prediction_value)
  File "F:\UI\venv\lib\site-packages\gradio\components.py", line 1860, in postprocess
    returned_format = y.split(".")[-1].lower()
AttributeError: 'tuple' object has no attribute 'split'
```

**Comment by kabachuha** [comment]
Got it, will fix in a few hours, once I get home
