### ISSUE TITLE
Did anyone Get it Running 

### ISSUE THREAD

**Issue by Pavankunchala** [deforum-art/sd-webui-modelscope-text2video#8]
I have an RTX 3080 16GB, But I am still unable to run it 

I am getting this error

```
Traceback (most recent call last):
  File "C:\Users\pavan\Desktop\Projects\Deep-Learning\webui\venv\lib\site-packages\gradio\routes.py", line 337, in run_predict
    output = await app.get_blocks().process_api(
  File "C:\Users\pavan\Desktop\Projects\Deep-Learning\webui\venv\lib\site-packages\gradio\blocks.py", line 1018, in process_api
    data = self.postprocess_data(fn_index, result["prediction"], state)
  File "C:\Users\pavan\Desktop\Projects\Deep-Learning\webui\venv\lib\site-packages\gradio\blocks.py", line 956, in postprocess_data
    prediction_value = block.postprocess(prediction_value)
  File "C:\Users\pavan\Desktop\Projects\Deep-Learning\webui\venv\lib\site-packages\gradio\components.py", line 1860, in postprocess
    returned_format = y.split(".")[-1].lower()
AttributeError: 'tuple' object has no attribute 'split'
```

**Comment by ryan94420** [comment]
got a similar error I think but its outputting images in stable-diffusion-webui\outputs\img2img-images\text2video-modelscope 
 so it is sort of working for me I can look at the images its made, but wont output a video into webui. sometimes seems like a bunch of noise not sure seems to be a prompt issue maybe

**Comment by Pavankunchala** [comment]
It is just generating random images right now, there is no coherence, 
I put this as the prompt: A Car running on water, I just got a bunch random images
