### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by willehlad** [deforum-art/sd-webui-modelscope-text2video#80]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### Are you using the latest version of the extension?

- [X] I have the modelscope text2video extension updated to the lastest version and I still have the issue.

### What happened?

  File "C:\Users\howv\Documents\A1111 Web UI Autoinstaller\stable-diffusion-webui\extensions\sd-webui-modelscope-text2video\scripts\modelscope-text2vid.py", line 160, in process
    samples, _ = pipe.infer(prompt, n_prompt, steps, frames, seed + batch if seed != -1 else -1, cfg_scale,
  File "C:\Users\howv\Documents\A1111 Web UI Autoinstaller\stable-diffusion-webui\extensions\sd-webui-modelscope-text2video\scripts\t2v_pipeline.py", line 255, in infer
    if 'CPU' in cpu_vae:
TypeError: argument of type 'NoneType' is not iterable
Exception occurred: argument of type 'NoneType' is not iterable

### Steps to reproduce the problem

1. Go to .... enter prompt
2. Press ....generate
3. ... error

### What should have happened?

surely generated a video

### WebUI and Deforum extension Commit IDs

webui commit id - commit: [3715ece0]
txt2vid commit id -not sure where to find it

### What GPU were you using for launching?

nvidia 2060 super 8gb

### On which platform are you launching the webui backend with the extension?

Local PC setup (Windows)

### Settings

![settings1](https://user-images.githubusercontent.com/113027238/228237931-4e3c9337-f8fa-4429-86ee-f555ba4c582b.jpg)

### Console logs

```Shell
Loading A111 WebUI Launcher
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
 i   Settings file found, loading
 →   Updating Settings File  ✓
 i   Launcher Version 1.7.0
 i   Found a custom WebUI Config
 i   No Launcher launch options
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
 →   Checking requirements :
 i   Python 3.10.7150.1013 found in registry:  C:\Users\howv\AppData\Local\Programs\Python\Python310\
 !   This is not the recommended version of Python and will probably cause errors
 i   Clearing PATH of any mention of Python
 →   Adding python 3.10 to path  ✓
 i   Git found and already in PATH:  C:\Program Files\Git\cmd\git.exe
 i   Automatic1111 SD WebUI found:  C:\Users\howv\Documents\A1111 Web UI Autoinstaller\stable-diffusion-webui
 i   One or more checkpoint models were found
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  Loading Complete, opening launcher
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
 i   Arguments are now: --xformers
 i   Arguments are now: --xformers
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  WEBUI LAUNCHING VIA EMS LAUNCHER, EXIT THIS WINDOW TO STOP THE WEBUI
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
 !   Any error happening after 'commit hash : XXXX' is not related to the launcher. Please report them on Automatic1111's github instead :
 ☁   https://github.com/AUTOMATIC1111/stable-diffusion-webui/issues/new/choose
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Cancel
venv "C:\Users\howv\Documents\A1111 Web UI Autoinstaller\stable-diffusion-webui\venv\Scripts\Python.exe"
Python 3.10.7 (tags/v3.10.7:6cc6b13, Sep  5 2022, 14:08:36) [MSC v.1933 64 bit (AMD64)]
Commit hash: 3715ece0adce7bf7c5e9c5ab3710b2fdc3848f39
Installing requirements for Web UI
Installing requirement for sd-webui-controlnet


Launching Web UI with arguments: --autolaunch --xformers
Loading weights [27a4ac756c] from C:\Users\howv\Documents\A1111 Web UI Autoinstaller\stable-diffusion-webui\models\Stable-diffusion\SD15NewVAEpruned.ckpt
Creating model from config: C:\Users\howv\Documents\A1111 Web UI Autoinstaller\stable-diffusion-webui\configs\v1-inference.yaml
LatentDiffusion: Running in eps-prediction mode
DiffusionWrapper has 859.52 M params.
Applying xformers cross attention optimization.
Textual inversion embeddings loaded(0):
Model loaded in 3.7s (load weights from disk: 1.2s, create model: 0.3s, apply weights to model: 0.3s, apply half(): 0.6s, move model to device: 0.5s, load textual inversion embeddings: 0.7s).
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
ModelScope text2video extension for auto1111 webui
Git commit: Unknown
Starting text2video
Pipeline setup
config namespace(framework='pytorch', task='text-to-video-synthesis', model={'type': 'latent-text-to-video-synthesis', 'model_args': {'ckpt_clip': 'open_clip_pytorch_model.bin', 'ckpt_unet': 'text2video_pytorch_model.pth', 'ckpt_autoencoder': 'VQGAN_autoencoder.pth', 'max_frames': 16, 'tiny_gpu': 1}, 'model_cfg': {'unet_in_dim': 4, 'unet_dim': 320, 'unet_y_dim': 768, 'unet_context_dim': 1024, 'unet_out_dim': 4, 'unet_dim_mult': [1, 2, 4, 4], 'unet_num_heads': 8, 'unet_head_dim': 64, 'unet_res_blocks': 2, 'unet_attn_scales': [1, 0.5, 0.25], 'unet_dropout': 0.1, 'temporal_attention': 'True', 'num_timesteps': 1000, 'mean_type': 'eps', 'var_type': 'fixed_small', 'loss_type': 'mse'}}, pipeline={'type': 'latent-text-to-video-synthesis'})
device cuda
Working in txt2vid mode
  0%|                                                                                            | 0/1 [00:00<?, ?it/s]latents torch.Size([1, 4, 24, 32, 32]) tensor(0.0010, device='cuda:0') tensor(0.9977, device='cuda:0')
DDIM sampling tensor(1): 100%|█████████████████████████████████████████████████████████| 31/31 [00:41<00:00,  1.35s/it]
Traceback (most recent call last):█████████████████████████████████████████████████████| 31/31 [00:41<00:00,  1.24s/it]
  File "C:\Users\howv\Documents\A1111 Web UI Autoinstaller\stable-diffusion-webui\extensions\sd-webui-modelscope-text2video\scripts\modelscope-text2vid.py", line 160, in process
    samples, _ = pipe.infer(prompt, n_prompt, steps, frames, seed + batch if seed != -1 else -1, cfg_scale,
  File "C:\Users\howv\Documents\A1111 Web UI Autoinstaller\stable-diffusion-webui\extensions\sd-webui-modelscope-text2video\scripts\t2v_pipeline.py", line 255, in infer
    if 'CPU' in cpu_vae:
TypeError: argument of type 'NoneType' is not iterable
Exception occurred: argument of type 'NoneType' is not iterable
```

**Comment by kabachuha** [comment]
Same as https://github.com/deforum-art/sd-webui-modelscope-text2video/issues/79
